--Basic init
-- rawset(_G, "__foxBot_1", {})

--VSCode Lua Language Server hints
---@class player_t
---foxBot AI Table
---@field ai table
---foxBot AI Owner
---@field ai_owner player_t
---foxBot Current followers
---@field ai_followers table
---foxBot Currently owned bots
---@field ai_ownedbots table
---foxBot Current AI ability override
---@field ai_override_abil number
---foxBot Current pick target mobj
---@field ai_picktarget mobj_t
---foxBot Current client-side AI controls setting
---@field ai_convarcontrols boolean
---foxBot Previous client-side AI controls setting
---@field ai_lastconvarcontrols boolean

---@class mobj_t
---foxBot PickTarget helper
---@field ai_player player_t
